apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-23T21:10:24Z"
  labels:
    run: eventappclient2
  name: eventclient-lb2
  namespace: default
  resourceVersion: "28467"
  selfLink: /api/v1/namespaces/default/services/eventclient-lb2
  uid: 87cfd4b2-f5d9-11e9-9e6d-42010a800099
spec:
  clusterIP: 10.27.248.129
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31222
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: deploy1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.197.171.9

